# This is a basic workflow to help you get started with Actions

name: Test On System

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          chmod +x install.sh,
          ./install.sh
